### ISSUE TITLE
Issues while installing dependencies for Gransk

### ISSUE THREAD

**Issue by Viseshini** [pcbje/gransk#11]
I have followed the instruction as mentioned in the read me to use gransk with the Python implementation.
I ran:
`python -m setup.py download`

It returns that `polygot` is not recognizes as a command.

So I try to install polyglot using
`pip install polyglot` and apparently it needs `pycld2` and `pyicu`
When I try to install pyciu(`pip isntall pyicu`) it returns an error
`Failed to build pyicu polyglot 16.7.4 requires pycld2>0.3, which is not installed`

When I try to install pycld2(`pip install pycld2`) it returns an error
`polyglot 16.7.4 requires pyICU>1.8, which is not installed`

I have referred other github issues too, to install icu, pyicu and pycld2 but with no success. 

I don't know how to proceed from here to install polyglot and start working with Gransk. Any help or guidance is appreciated.

**Comment by oaeide** [comment]
Are you using WSL? This works for me on WSL (Ubuntu 16.04.5 LTS):

`
sudo apt-get install python-numpy libicu-dev && sudo pip3 install pyicu
`

**Comment by IamMohitM** [comment]
No I'm just using the regular windows

**Comment by oaeide** [comment]
In that case, I do believe this will be the solution for you [#91 comment](https://github.com/aboSamoor/polyglot/issues/91#issuecomment-382444800)

**Comment by IamMohitM** [comment]
Yes thank you that installed polyglot. But when I run it(`polyglot`) on command line it returns:

`pkg_resources.DistributionNotFound: The 'pycld2>=0.3' distribution was not found and is required by polyglot`

When I try: `pip3 install pycld2`, it returns:
```
Failed building wheel for pycld2
Failed to build pycld2
polyglot 16.7.4 requires PyICU>=1.8, which is not installed.
```

When I try `pip3 intall pyicu`, it returns:

```
Failed building wheel for pyicu
Running setup.py clean for pyicu
Failed to build pyicu
polyglot 16.7.4 requires pycld2>=0.3, which is not installed.
```

This is Catch 22. I don't know how to install both.

**Comment by IamMohitM** [comment]
> In that case, I do believe this will be the solution for you [#91 comment](https://github.com/aboSamoor/polyglot/issues/91#issuecomment-382444800)

Corrections:

This actually solved my issue. I just had to install pyicu and pycld2using using the binaries

Got the pyicu and pycld2 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyicu

Installed morfessor using the tar.gz file from there website and pip

`pip install morfessor-2.0.3.tar.gz`

**Comment by pcbje** [comment]
Thanks Øyvind and others! Closing
